articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('new/', views.new),
    path('create/', views.create),
    path('<int:article_pk>/', views.detail),
    path('<int:article_pk>/delete/', views.delete),
    path('<int:article_pk>/edit/', views.edit),
    path('<int:article_pk>/update/', views.update),
]

django_pair/start/urls.py
from django.urls import path
from . import views

app_name = 'start'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('detail/<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/commentcreate/', views.commentcreate, name='commentcreate'),
    path('<int:article_pk>/commentdelete/<int:comment_pk>', views.commentdelete, name='commentdelete')
]

django_pair/team/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('start/', include('start.urls'))
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns  = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
]

reboot/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.
# Reporter(1) - Article(N)
# reporter - name
class Reporter(models.Model):
    name = models.CharField(max_length=10)

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

# Article(1) - Comment(N) 
# comment - content
class Comment(models.Model):
    content = models.CharField(max_length=150)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

django_pair/start/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.CharField(max_length=10)
    job = models.TextField()

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from IPython import embed

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def create(request):
    article = Article()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.image = request.FILES.get('image')
    # articles.created_at = request.GET.get('created_at')
    # articles.updated_at = request.GET.get('updated_at')
    article.save()
    # embed()

    return redirect('/articles/')

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()

    return redirect('/articles/')

def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    # if article.title != request.GET.get('title') or article.content != request.GET.get('content'): 없어도 가능합니다?
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    
    return redirect(f'/articles/{article_pk}')

django_pair/start/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .form import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'index.html', context)

def new(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article_form.save()
            return redirect('/start/')
    else:
        article_form = ArticleForm()
        context = {
            'article_form': article_form
        }
        return render(request, 'form.html', context)

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comment_form = CommentForm()
    comments = Comment.objects.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments
    }
    return render(request, 'detail.html', context)

def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            article = article_form.save()
            return redirect(f'/start/detail/{article_pk}')
    else:
        article_form = ArticleForm(instance=article)
        context = {
            'article_form': article_form
        }
        return render(request, 'update.html', context)

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        article.delete()
        return redirect('/start/')
    else:
        return redirect(f'/start/detail/{article_pk}')

def commentcreate(request, article_pk):
    if request.method == 'POST':
        article = Article.objects.get(pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.save()
    return redirect(f'/start/detail/{article_pk}')

def commentdelete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()

    return redirect(f'/start/detail/{article_pk}')

jobs/views.py
from django.shortcuts import render
from faker import Faker
from .models import Job
import requests
from decouple import config
# Create your views here.

fake = Faker()

def index(request):
    return render(request, 'jobs/index.html')

def create(request):
    name = request.POST.get('name')
    if not Job.objects.filter(name=name):
        people = Job()
        people.name = name
        people.job = fake.job() 
        people.save()
    else:
        people = Job.objects.get(name=name)

    # 직업 결과에 따라, giphy 요청
    job = people.job
    api_key = config('GIPHY_API_KEY')
    url = f'http://api.giphy.com/v1/gifs/search?api_key={api_key}&q={job}&lang=en'

    response = requests.get(url).json()
    try:
        image_url = response['data'][0]['images']['original']['url']
    except:
        image_url = None

    context = {
        'people': people,
        'image_url': image_url,
    }
    return render(request, 'jobs/create.html', context)

articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시판</title>
  {% block css %}
  {% endblock %}
  <style>
    a {
      text-decoration: none;
    }
    
    body {
      background-image: url({% static "background.jpg" %});
      background-size: cover;
      padding: 15px;
    }
  </style>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class=text-center>
  {% block body %}

  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}

{% block body %}
<div class="jumbotron jumbotron-fluid container shadow-sm p-3 mb-5 bg-white rounded">
  <div class="container">
    <h1 class="display-5">{{ article.title }}</h1>
    <br>
    <img src="{{ article.image.url }}" alt="{{ article.image.name }}">
    <p class="lead">{{ article.content }}</p>
    <hr>  
    <pre><a href="edit/">수정</a>  <a href="delete/">삭제</a>  <a href="/articles/">목록으로</a></pre>
    <hr>
    <p>작성일자: {{ article.created_at }}</p>
    <p>수정일자: {{ article.updated_at }}</p>
  </div>
</div>
{% endblock %}

articles/templates/articles/edit.html
{% extends 'articles/base.html' %}

{% block body %}
<div class="container">
  <form action="/articles/{{ article.pk }}/update/" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="title"><h4>제목</h4></label>
      <input type="text" name="title" class="form-control" id="title" value="{{ article.title }}">
    </div>
    <div class="form-group">
      <label for="content"><h4>내용</h4></label>
      <textarea class="form-control" name="content" id="content" rows="10">{{ article.content }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">수정!</button>
    <a href="/articles/{{ article.pk }}"><button type="button" class="btn btn-dark">취소</button></a>
  </form>
</div>
{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}

{% block body %}
<div class="container">
  <pre><h2 class="display-3">게시판(board)</h2></pre>
</div>
<div class='container jumbotron bg-light rounded-lg border border-warning'>
  <h4><a href="new/"  class="text-primary">새로운 글</a></h4>
  <br>
  {% for article in articles %}
  <h3><a class="display-4 text-dark" href="{{ article.pk }}/">{{ article.pk }}. {{ article.title }}</a></h3>
  <p class="lead">{{ article.created_at }}</p>
  {% endfor %}
</div>
  
{% endblock %}

articles/templates/articles/new.html
{% extends 'articles/base.html' %}

{% block body %}
<div class="container">
  <form action="/articles/create/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="title"><h4>제목</h4></label>
      <input type="text" name="title" class="form-control" id="title">
    </div>
    <div class="form-group">
      <label for="content"><h4>내용</h4></label>
      <textarea class="form-control" name="content" id="content" rows="10"></textarea>
    </div>
    <label for="image">이미지</label>
    <input type="file" name="image" id="image">
    <button type="submit" class="btn btn-primary">등록!</button>
    <a href="/articles/"><button type="button" class="btn btn-dark">취소</button></a>
  </form>
</div>
{% endblock %}

django_pair/start/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  
  {% block css %}
  {% endblock %}
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>

django_pair/start/templates/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>{{ article.title }}</h1>
<hr>
<p>{{ article.content }}</p>
<p>{{ article.created_at }}</p>
<a href="{% url 'start:update' article.pk %}">글 수정</a>
<form action="{% url 'start:delete' article.pk %}" method="POST" onclick="return confirm('정말 삭제하시겠습니까?')">
  {% csrf_token %}
  <input type="submit" value="삭제">
</form>
<a href="{% url 'start:index' %}">목록으로</a>


<hr>
<form action="{% url 'start:commentcreate' article.pk %}" method="POST">
  {% csrf_token %}
  {{ comment_form.content }}
  <br>
  <input type="submit" value="작성">
</form>

{% for comment in comments %}
<hr>  
<p>{{ comment.content }}</p>
<p>{{ comment.created_at }}</p>
<a href="{% url 'start:commentdelete' article.pk comment.pk %}">삭제</a>
{% empty %}
<p>댓글이 없어요!T^T</p>
{% endfor %}

{% endblock %}

django_pair/start/templates/form.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
  {% csrf_token %}

  {{ article_form.title }}
  <br>
  {{ article_form.content}}
  <br>
  <input type="submit" value="작성하기">  
</form>
{% endblock %}

django_pair/start/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
  body {
    background-image: url("{% static 'sponge.jpg' %}");
  }
</style>
{% endblock %}

{% block body %}
<h1>HELLO</h1>
<a href="{% url 'start:new' %}">글 작성</a>
{% for article in articles %}

<a href="detail/{{ article.pk }}/"><h3>{{ article.pk }}. {{ article.title }}</h3></a>
<p>{{ article.created_at }}</p>
{% endfor %}
{% endblock %}

django_pair/start/templates/update.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
  {% csrf_token %}

  {{ article_form.title }}
  <br>
  {{ article_form.content}}
  <br>
  <input type="submit" value="작성하기">  
</form>
{% endblock %}

jobs/templates/jobs/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {% block body%}
  
  {% endblock%}
</body>
</html>

jobs/templates/jobs/create.html
{% extends 'jobs/base.html' %}
{% block body %}

<p><strong>{{ people.name }}</strong> 님은 전생에 <strong>{{ people.job }}</strong> 이었습니다.</p>
<img src="{{ image_url }}" alt="{{ people.job }}">

{% endblock%}

jobs/templates/jobs/index.html
{% extends 'jobs/base.html' %}
{% block body %}

<h1>전생에 나는?</h1>

<form action="{% url 'jobs:create' %}" method="POST">
  {% csrf_token %}
  <label for="name">이름 : </label>
  <input type="text" name="name" id="name">
  <input type="submit" value="확인!!!"">
</form>

{% endblock %}